name = "Pokecalvice"
author = "Bolofofodoidao/Mori"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a380e0406034c4b4f3fef023a1638edb1c22b4b6f87bb36832e9405b9fc9763"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
acceptable-game-versions = ["fabric"]
