name = "Pokecalvice"
author = "Bolofofodoidao/Mori"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b7b0378e43ea534dbc41ee30629d98da4f1cacde147487d1b63e73fd5a0e653"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
acceptable-game-versions = ["fabric"]
